swagger: "2.0"
info:
  description: "API template"
  version: "0.0.0"
  title: "API template"
host: "localhost:3000"
basePath: "/api/v1"
produces:
  - "application/json"
securityDefinitions:
  authorization:
    type: apiKey
    name: authorization
    in: header
paths:
  /books/{bookRef}:
    parameters:
      - in: path
        name: bookRef
        schema:
          type: integer
          example: 1
        description: The id of the book to return.
        required: true
    get:
      summary: Returns a book.
      tags:
        - books
      responses:
        '200':
          description: The book.
        '404':
          $ref: '#components/responses/NotFound'
    put:
      summary: Replaces a book.
      tags:
        - books
      parameters:
        - in: body
          name: Book
          required: true
          description: The new book.
          schema:
            $ref: "#/definitions/Book"
      responses:
        '200':
          description: The new book.
        '400':
          $ref: '#components/responses/BadRequest'
        '404':
          $ref: '#components/responses/NotFound'
    patch:
      summary: Updates a book.
      tags:
        - books
      parameters:
        - in: body
          name: Book
          required: true
          description: The new book data.
          schema:
            $ref: "#/definitions/Book"
      responses:
        '200':
          description: The book updated.
        '404':
          $ref: '#components/responses/NotFound'
    delete:
      summary: Deletes a book.
      tags:
        - books
      responses:
        '200':
          description: Deleted.
        '404':
          $ref: '#components/responses/NotFound'
  /books:
    post:
      summary: Adds a new book.
      tags:
        - books
      parameters:
        - name: Book
          in: body
          required: true
          description: The book to create.
          schema:
            $ref: "#/definitions/Book"
      responses:
        '201':
          description: Book created.
        '400':
          $ref: '#components/responses/BadRequest'
        '409':
          $ref: '#components/responses/Conflict'
    get:
      summary: Returns a list of books.
      tags:
        - books
      parameters:
        - in: query
          name: title
          schema:
            type: string
            example: "Comment faire ?"
          description: The title of books to return.
        - in: query
          name: authorId
          schema:
            type: integer
            example: 1
          description: The author id of books to return.
        - in: query
          name: publicationYear
          schema:
            type: string
            example: "2019"
          description : The publication year of books to return.
        - in: query
          name: editorId
          schema:
            type: integer
            example: 1
          description: The editor id of books to return.
        - in: query
          name: genre
          schema:
            type: string
            example: "Thriller"
          description: The genre of books to return.
      responses:
        '200':
          description: The list of books.
        '404':
          description: No books found.
components:
  responses:
    Conflict:
      description: Conflict.
    BadRequest:
      description: Bad input parameter.
    NotFound:
      description: Resource not found.
  examples:
    authorExample:
      value:
        id: 1
        lastName: "Verne"
        firstName: "Jules"
      summary: A sample author.
    editorExample:
      value:
        id: 1
        name: "Poches éditions"
definitions:
  Editor:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        example: 1
        description: The editor id.
      name:
        type: string
        example: "Poches éditions"
        description: The editor name.
  Event:
    type: object
    required:
      - id
      - date
      - description
      - title
    properties:
      id:
        type: integer
        example: 1
        description: The event id.
      date:
        type: string
        format: date
        example: '2019-02-22'
        description: The event date.
      description:
        type: string
        example: "Rencontre avec l'auteure vietnamienne Thuy Linh Ti Ngo."
        description: The event description.
      title:
        type: string
        example: "À la découverte du Vietnam"
        description: The event title.
  Award:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        example: 1
        description: The award id.
      name:
        type: string
        example: "Prix Goncourt"
        description: The award name.
  Author:
    type: object
    required:
      - id
      - lastName
      - firstName
    properties:
      id:
        type: integer
        example: 1
        description: The author id.
      lastName:
        type: string
        example: "Verne"
        description: The author last name.
      firstName:
        type: string
        example: "Jules"
        description: The author first name.
      biography:
        type: string
        example: "Biographie : Jules Verne est un écrivain français, dont une grande partie de l'œuvre est consacrée à
        des romans d'aventures et de science-fiction."
        description: The author biography.
        default: null
      awards:
        type: array
        items:
          type: object
        example: [{id: 1, name: "Prix Goncourt"}, {id: 2, name: "Prix Renaudot"}]
        description: The author awards.
  Genre:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        example: 1
        description: The genre id.
      name:
        type: string
        example: "Thriller"
        description: The genre name.
  Book:
    type: object
    required:
      - title
      - author
      - editor
      - bookRef
      - publicationYear
      - price
      - genre
    properties:
      title:
        type: string
        example: "Le tour du monde en 80 jours"
        description: The book title.
      author:
        type: object
        example: {id: 1, lastName: "Verne", firstName: "Jules"}
        description: The book author.
        schema:
          $ref: "#/definitions/Author"
      editor:
        type: object
        schema:
          $ref: "#/definitions/Editor"
        example: '#components/examples/editorExample'
        description: The book editor.
      bookRef:
        type: integer
        example: 9782330053901
        description: The book reference.
      publicationYear:
        type: string
        example: "2019"
        description: The book publication year.
      price:
        type: number
        example: 8.00
        description: The book price.
      genre:
        type: array
        items:
          type: object
        example: [{id: 1, name: "Aventure"}, {id: 2, name: "Thriller"}]
        description: The book genre.
      summary:
        type: string
        example: "Phileas Fogg, parfait gentleman anglais, membre du Reform club est un homme froid,
        ponctuel etméticuleux, mais aussi généreux et courageux."
        description: The book summary.
        default: null
      editorWord:
        type: string
        example: "Sûrement l'une de ses meilleures oeuvres."
        description: What the editor says about this book.
        default: null
      booksellerWord:
        type: string
        example: "L'un de nos coups de coeur 2019 !"
        description: What the bookseller says about this book.
        default: null
      details:
        type: object
        properties:
          pagesNumber:
            type: integer
            example: 380
            description: The book pages number.
            default: null
          length:
            type: integer
            example: 240
            description: The book length in millimeters.
            default: null
          width:
            type: integer
            example: 145
            description: The book width in millimeters.
            default: null
          thickness:
            type: integer
            example: 15
            description: The book thickness in millimeters.
            default: null
          weight:
            type: integer
            example: 640
            description: The book weight in gramms.
            default: null


